#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 || " $* " == *" --help "* ]]; then
  echo "Usage: mmex_ln <as_user> <src> <dest>" >&2
  exit 1
fi

as_user="$1"
src="$2"
dest="$3"

pquery --cmd=ln "$as_user" "$src" "$dest" --silent
