#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 || " $* " == *" --help "* ]]; then
  echo "Usage: mmex_chmod <as_user> <mode> <path>" >&2
  exit 1
fi

as_user="$1"
mode="$2"
path="$3"

pquery --cmd=chmod "$as_user" "$mode" "$path" --silent
