#!/usr/bin/env bash
set -euo pipefail

if [[ $# -gt 1 || " $* " == *" --help "* ]]; then
  echo "Usage: mmex_umask [mask]" >&2
  exit 1
fi

if [[ $# -eq 1 ]]; then
  pquery --cmd=umask "$1" --silent
else
  pquery --cmd=umask
fi
