#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 || " $* " == *" --help "* ]]; then
  echo "Usage: mmex_cat <as_user> <path>" >&2
  exit 1
fi

pquery --cmd=readfile "$1" "$2" --json | jq -r '.raw'
