#!/usr/bin/env bash
set -euo pipefail

# require at least user and path
if [[ $# -lt 2 || $# -gt 3 || " $* " == *" --help "* ]]; then
  echo "Usage: debi_mkdir <as_user> <path> [mode]" >&2
  exit 1
fi

as_user="$1"
path="$2"
mode="${3:-}"

if [[ -z $mode ]]; then
  sudo -u "$as_user" mkdir "$path"  
else
  sudo -u "$as_user" mkdir -m "$mode" "$path"  
fi
