#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 || " $* " == *" --help "* ]]; then
  echo "Usage: debi_ls <as_user> <path>" >&2
  exit 1
fi

as_user="$1"
path="$2"

sudo -u "$as_user" ls "$path" 2>/dev/null || exit 1
