CREATE TABLE IF NOT EXISTS groups (
  "group_id" SERIAL PRIMARY KEY,
  "group" TEXT UNIQUE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER set_updated_at BEFORE
UPDATE ON groups FOR EACH ROW
EXECUTE FUNCTION updated_at ();

