CREATE TABLE IF NOT EXISTS user_groups (
  "user_group_id" SERIAL PRIMARY KEY,
  "user_id" INT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
  "group_id" INT REFERENCES groups (group_id) ON DELETE CASCADE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT UNIQUE_USER_GROUP_PAIR UNIQUE (user_id, group_id)
);

CREATE TRIGGER set_updated_at BEFORE
UPDATE ON user_groups FOR EACH ROW
EXECUTE FUNCTION updated_at ();

-- INSERT INTO
--   user_groups (user_id, group_id)
-- VALUES
--   (1, 1);
